# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-20 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0007_webauthndevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u2fdevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='U2FDevice',
        ),
    ]
